// MachineMind Portfolio Projects Data

export type ProjectCategory = "flagship" | "demo" | "automation" | "enterprise";

export interface Project {
  slug: string;
  nameEs: string;
  nameEn: string;
  taglineEs: string;
  taglineEn: string;
  descriptionEs?: string;
  descriptionEn?: string;
  category: ProjectCategory;
  subcategory?: string;
  techStack: string[];
  liveUrl: string | null;
  thumbnailUrl?: string;
  colorAccent: string;
  isActive: boolean;
  isFeatured: boolean;
}

export const projects: Project[] = [
  // ============================================
  // FLAGSHIP PROJECTS
  // ============================================
  {
    slug: "movvia",
    nameEs: "Movvia",
    nameEn: "Movvia",
    taglineEs: "Concierge de lujo para Cartagena",
    taglineEn: "Luxury concierge for Cartagena",
    descriptionEs:
      "Plataforma completa de hospitalidad con reservas, experiencias de lujo, checkout y gestión de restaurantes.",
    descriptionEn:
      "Complete hospitality platform with bookings, luxury experiences, checkout, and restaurant management.",
    category: "flagship",
    subcategory: "hospitality",
    techStack: [
      "Next.js 16",
      "Supabase",
      "Tailwind",
      "Wompi",
      "Twilio",
      "Claude AI",
    ],
    liveUrl: "https://movvia-pi.vercel.app",
    colorAccent: "#00B4FF",
    isActive: true,
    isFeatured: true,
  },
  {
    slug: "simmer-down",
    nameEs: "Simmer Down Pizza",
    nameEn: "Simmer Down Pizza",
    taglineEs: "Pizzería con Sofia AI integrado",
    taglineEn: "Pizzeria with integrated Sofia AI",
    descriptionEs:
      "Sistema de pedidos con partículas de fuego, easter eggs, menú secreto Konami y etiquetas dietéticas.",
    descriptionEn:
      "Ordering system with fire particles, easter eggs, Konami secret menu, and dietary tags.",
    category: "flagship",
    subcategory: "restaurant",
    techStack: ["Next.js 16", "Supabase", "Zustand", "Framer Motion", "Canvas"],
    liveUrl: "https://simmer-down.vercel.app",
    colorAccent: "#f97316",
    isActive: true,
    isFeatured: true,
  },
  {
    slug: "aegis-shield",
    nameEs: "AEGIS Shield",
    nameEn: "AEGIS Shield",
    taglineEs: "Control de acceso militar con IA",
    taglineEn: "Military access control with AI",
    descriptionEs:
      "Sistema de control de acceso militar con DBIDS, Sentinel AI y gestión de políticas de fecha.",
    descriptionEn:
      "Military access control system with DBIDS, Sentinel AI, and date-based policy management.",
    category: "enterprise",
    subcategory: "security",
    techStack: ["Next.js 14", "Supabase", "DBIDS", "Sentinel AI", "bcrypt"],
    liveUrl: null,
    colorAccent: "#1c4a5e",
    isActive: true,
    isFeatured: false,
  },

  // ============================================
  // DEMO PROJECTS
  // ============================================
  {
    slug: "demo-100luxury",
    nameEs: "100 Luxury",
    nameEn: "100 Luxury",
    taglineEs: "Marca de hospitalidad de lujo",
    taglineEn: "Luxury hospitality brand",
    category: "demo",
    subcategory: "hospitality",
    techStack: ["Next.js 16", "Tailwind"],
    liveUrl: "https://demo-100luxury.vercel.app",
    colorAccent: "#00B4FF",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-aerotransfer",
    nameEs: "AeroTransfer",
    nameEn: "AeroTransfer",
    taglineEs: "Servicio de charter y transfers",
    taglineEn: "Charter and transfer service",
    category: "demo",
    subcategory: "transport",
    techStack: ["Next.js 16", "Tailwind", "Framer Motion"],
    liveUrl: "https://demo-aerotransfer.vercel.app",
    colorAccent: "#2563eb",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-benzdriver",
    nameEs: "BenzDriver",
    nameEn: "BenzDriver",
    taglineEs: "Transporte premium ejecutivo",
    taglineEn: "Premium executive transport",
    category: "demo",
    subcategory: "transport",
    techStack: ["Next.js 16", "Tailwind"],
    liveUrl: "https://demo-benzdriver.vercel.app",
    colorAccent: "#171717",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-blacksound",
    nameEs: "BlackSound",
    nameEn: "BlackSound",
    taglineEs: "Entretenimiento y vida nocturna",
    taglineEn: "Entertainment and nightlife",
    category: "demo",
    subcategory: "nightlife",
    techStack: ["Next.js 16", "Tailwind"],
    liveUrl: "https://demo-blacksound.vercel.app",
    colorAccent: "#9333ea",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-fourseasons-bogota",
    nameEs: "Four Seasons Bogotá",
    nameEn: "Four Seasons Bogotá",
    taglineEs: "Demo de hotel de lujo con Claude AI",
    taglineEn: "Luxury hotel demo with Claude AI",
    category: "demo",
    subcategory: "hospitality",
    techStack: ["Next.js 16", "Claude AI SDK", "Tailwind"],
    liveUrl: "https://demo-fourseasons-bogota.vercel.app",
    colorAccent: "#00B4FF",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-jota-pardo",
    nameEs: "Jota Pardo",
    nameEn: "Jota Pardo",
    taglineEs: "Servicios de concierge personal",
    taglineEn: "Personal concierge services",
    category: "demo",
    subcategory: "concierge",
    techStack: ["Next.js 16", "Tailwind"],
    liveUrl: "https://demo-jota-pardo.vercel.app",
    colorAccent: "#0ea5e9",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-medellinvip",
    nameEs: "Medellín VIP",
    nameEn: "Medellín VIP",
    taglineEs: "Turismo VIP en Medellín",
    taglineEn: "VIP tourism in Medellín",
    category: "demo",
    subcategory: "tourism",
    techStack: ["Next.js 16", "Tailwind"],
    liveUrl: "https://demo-medellinvip.vercel.app",
    colorAccent: "#f59e0b",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-osaka-nikkei",
    nameEs: "Osaka Nikkei Bogotá",
    nameEn: "Osaka Nikkei Bogotá",
    taglineEs: "Restaurante japonés con Sofia AI",
    taglineEn: "Japanese restaurant with Sofia AI",
    category: "demo",
    subcategory: "restaurant",
    techStack: ["Next.js 16", "Sofia AI", "Tailwind"],
    liveUrl: "https://demo-osaka-nikkei.vercel.app",
    colorAccent: "#dc2626",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-angelica-valencia",
    nameEs: "Angelica Valencia",
    nameEn: "Angelica Valencia",
    taglineEs: "Concierge personal de lujo",
    taglineEn: "Luxury personal concierge",
    category: "demo",
    subcategory: "concierge",
    techStack: ["Next.js 16", "Tailwind"],
    liveUrl: "https://demo-angelica-valencia.vercel.app",
    colorAccent: "#ec4899",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "dharma",
    nameEs: "Dharma Beach Club",
    nameEn: "Dharma Beach Club",
    taglineEs: "Club de playa de lujo en Islas del Rosario",
    taglineEn: "Luxury beach club in Islas del Rosario",
    descriptionEs:
      "Experiencia de día completo con transporte en lancha, gastronomía gourmet, y conexión espiritual en el Caribe colombiano.",
    descriptionEn:
      "Full day experience with boat transportation, gourmet gastronomy, and spiritual connection in the Colombian Caribbean.",
    category: "demo",
    subcategory: "hospitality",
    techStack: ["Next.js 16", "Supabase", "Stripe", "Framer Motion", "Zustand"],
    liveUrl: "https://dharma-topaz.vercel.app",
    colorAccent: "#d4af37",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-alambique",
    nameEs: "Alambique Medellín",
    nameEn: "Alambique Medellín",
    taglineEs: "Laboratorio Cocina & Bar rooftop",
    taglineEn: "Rooftop kitchen & bar laboratory",
    descriptionEs:
      "Restaurante rooftop con Sofia AI para reservaciones, gestión de reputación e integración Instagram.",
    descriptionEn:
      "Rooftop restaurant with Sofia AI for reservations, reputation management, and Instagram integration.",
    category: "demo",
    subcategory: "restaurant",
    techStack: ["Next.js 16", "React 19", "Tailwind v4", "Sofia AI"],
    liveUrl: "https://demo-alambique.vercel.app",
    colorAccent: "#8b5cf6",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-cafenoir",
    nameEs: "Café Noir Bar & Lounge",
    nameEn: "Café Noir Bar & Lounge",
    taglineEs: "Brunch epicentro de Getsemaní",
    taglineEn: "Getsemaní's brunch epicenter",
    descriptionEs:
      "Café y bar con Sofia AI, gestión de reputación, email marketing y e-commerce.",
    descriptionEn:
      "Café and bar with Sofia AI, reputation management, email marketing, and e-commerce.",
    category: "demo",
    subcategory: "restaurant",
    techStack: ["Next.js 16", "React 19", "Tailwind v4", "Sofia AI"],
    liveUrl: "https://demo-cafenoir.vercel.app",
    colorAccent: "#1c1917",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-confort",
    nameEs: "Confort Rent a Car",
    nameEn: "Confort Rent a Car",
    taglineEs: "Renta segura, respuestas rápidas con Sofia AI",
    taglineEn: "Safe rental, fast responses with Sofia AI",
    descriptionEs:
      "Sistema de renta de autos con Sofia AI WhatsApp, gestión de reputación multi-plataforma.",
    descriptionEn:
      "Car rental system with Sofia AI WhatsApp, multi-platform reputation management.",
    category: "demo",
    subcategory: "transport",
    techStack: ["Next.js 16", "React 19", "Tailwind v4", "Sofia AI", "Twilio"],
    liveUrl: "https://demo-confort.vercel.app",
    colorAccent: "#059669",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-lakasta",
    nameEs: "LA KASTA Premium Grill",
    nameEn: "LA KASTA Premium Grill",
    taglineEs: "Vive una experiencia alrededor del fuego",
    taglineEn: "Experience surrounded by fire",
    descriptionEs:
      "Parrilla premium con Sofia AI, analytics dashboard, multi-location support.",
    descriptionEn:
      "Premium grill with Sofia AI, analytics dashboard, multi-location support.",
    category: "demo",
    subcategory: "restaurant",
    techStack: [
      "Next.js 16",
      "React 19",
      "Tailwind v4",
      "Framer Motion",
      "Zustand",
    ],
    liveUrl: "https://demo-lakasta.vercel.app",
    colorAccent: "#b91c1c",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-mariaeu",
    nameEs: "María EU",
    nameEn: "María EU",
    taglineEs: "Consultoría con IA integrada",
    taglineEn: "AI-powered consulting",
    category: "demo",
    subcategory: "consulting",
    techStack: ["Next.js 16", "React 19", "Tailwind v4", "Anthropic SDK"],
    liveUrl: "https://demo-mariaeu.vercel.app",
    colorAccent: "#6366f1",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-nextproducciones",
    nameEs: "Next Producciones",
    nameEn: "Next Producciones",
    taglineEs: "Producción audiovisual con IA",
    taglineEn: "AI-powered audiovisual production",
    category: "demo",
    subcategory: "media",
    techStack: [
      "Next.js 16",
      "React 19",
      "Tailwind v4",
      "Anthropic SDK",
      "Zustand",
    ],
    liveUrl: "https://demo-nextproducciones.vercel.app",
    colorAccent: "#0ea5e9",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-rizos",
    nameEs: "Rizos Hair Care",
    nameEn: "Rizos Hair Care",
    taglineEs: "Soluciones inteligentes para el cuidado del cabello",
    taglineEn: "Smart hair care solutions",
    category: "demo",
    subcategory: "beauty",
    techStack: ["Next.js 16", "React 19", "Tailwind v4", "Anthropic SDK"],
    liveUrl: "https://demo-rizos.vercel.app",
    colorAccent: "#db2777",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-seven7times",
    nameEs: "SEVEN 7 TIMES Disco Club",
    nameEn: "SEVEN 7 TIMES Disco Club",
    taglineEs: "El disco club más grande del Caribe Colombiano",
    taglineEn: "Largest disco club in Colombian Caribbean",
    descriptionEs:
      "Discoteca con Sofia AI, calculador de ingresos perdidos, showcase de ambientes.",
    descriptionEn:
      "Nightclub with Sofia AI, revenue leak calculator, environments showcase.",
    category: "demo",
    subcategory: "nightlife",
    techStack: ["Next.js 16", "React 19", "Tailwind v4", "Sofia AI"],
    liveUrl: "https://demo-seven7times.vercel.app",
    colorAccent: "#d4af37",
    isActive: true,
    isFeatured: true,
  },
  {
    slug: "demo-tutaina",
    nameEs: "Tutaína Experiencias",
    nameEn: "Tutaína Experiences",
    taglineEs: "Experiencias culturales auténticas",
    taglineEn: "Authentic cultural experiences",
    category: "demo",
    subcategory: "tourism",
    techStack: ["Next.js 15", "React 19", "Tailwind v4", "Anthropic SDK"],
    liveUrl: "https://demo-tutaina.vercel.app",
    colorAccent: "#f59e0b",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "demo-villareal",
    nameEs: "Villa Real Villeta",
    nameEn: "Villa Real Villeta",
    taglineEs: "Tu escape de Bogotá con vistas inolvidables",
    taglineEn: "Your escape from Bogotá with unforgettable views",
    descriptionEs:
      "Villa de lujo con Sofia AI, pricing dinámico, automatización de journey del huésped.",
    descriptionEn:
      "Luxury villa with Sofia AI, dynamic pricing, guest journey automation.",
    category: "demo",
    subcategory: "real-estate",
    techStack: ["Next.js 16", "React 19", "Tailwind v4", "Sofia AI"],
    liveUrl: "https://demo-villareal.vercel.app",
    colorAccent: "#16a34a",
    isActive: true,
    isFeatured: true,
  },
  {
    slug: "demo-worldlion",
    nameEs: "World Lion Tours",
    nameEn: "World Lion Tours",
    taglineEs: "Tours auténticos de Comuna 13 con guías locales",
    taglineEn: "Authentic Comuna 13 tours with local guides",
    descriptionEs:
      "Operador turístico con León AI, calculador de impacto, showcase de reseñas.",
    descriptionEn:
      "Tour operator with León AI concierge, impact calculator, review showcase.",
    category: "demo",
    subcategory: "tourism",
    techStack: ["Next.js 16", "React 19", "Tailwind v4", "León AI"],
    liveUrl: "https://demo-worldlion.vercel.app",
    colorAccent: "#f97316",
    isActive: true,
    isFeatured: true,
  },
  {
    slug: "libertario",
    nameEs: "Libertario Coffee",
    nameEn: "Libertario Coffee",
    taglineEs: "Tu BariRockStar Virtual 24/7 en WhatsApp",
    taglineEn: "Your Virtual BariRockStar 24/7 on WhatsApp",
    descriptionEs:
      "Café especialidad con bot WhatsApp AI, soporte bilingüe, generación de reseñas.",
    descriptionEn:
      "Specialty coffee with WhatsApp AI bot, bilingual support, review generation.",
    category: "demo",
    subcategory: "restaurant",
    techStack: ["Next.js 16", "React 19", "Tailwind v4", "WhatsApp AI"],
    liveUrl: "https://libertario-demo.vercel.app",
    colorAccent: "#78350f",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "integrity-cleaning",
    nameEs: "Integrity Cleaning Las Vegas",
    nameEn: "Integrity Cleaning Las Vegas",
    taglineEs: "Limpieza premium para Henderson y Las Vegas",
    taglineEn: "Premium cleaning for Henderson & Las Vegas",
    descriptionEs:
      "Servicio de limpieza con calculador de cotizaciones, horarios extendidos para casino workers.",
    descriptionEn:
      "Cleaning service with quote calculator, extended hours for casino workers.",
    category: "demo",
    subcategory: "services",
    techStack: ["Next.js 16", "React 19", "Tailwind v4", "Supabase"],
    liveUrl: "https://integrity-cleaning.vercel.app",
    colorAccent: "#0284c7",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "tu-tataumana",
    nameEs: "Tu Tataúmana",
    nameEn: "Tu Tataúmana",
    taglineEs: "Tours con reservas automáticas por WhatsApp",
    taglineEn: "Tours with automatic WhatsApp bookings",
    descriptionEs:
      "Operador turístico con Sofia AI que reserva tours, responde preguntas y convierte visitantes 24/7.",
    descriptionEn:
      "Tour operator with Sofia AI that books tours, answers questions, and converts visitors 24/7.",
    category: "flagship",
    subcategory: "tourism",
    techStack: ["Next.js 16", "Sofia AI", "WhatsApp", "Supabase"],
    liveUrl: "https://tu-tataumana.vercel.app",
    colorAccent: "#0d9488",
    isActive: true,
    isFeatured: true,
  },

  // ============================================
  // SOFIA AI PLATFORMS (NEW)
  // ============================================
  {
    slug: "sofia-nevada",
    nameEs: "Sofia Nevada",
    nameEn: "Sofia Nevada",
    taglineEs: "Gestión de reputación con IA",
    taglineEn: "AI reputation management",
    descriptionEs:
      "Plataforma de gestión de reputación con monitoreo de reseñas y WhatsApp.",
    descriptionEn:
      "Reputation management platform with review monitoring and WhatsApp.",
    category: "automation",
    subcategory: "reputation",
    techStack: ["Next.js 16", "Supabase", "Anthropic SDK", "Twilio"],
    liveUrl: "https://sofia-nevada.vercel.app",
    colorAccent: "#7c3aed",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "sofia-realestate",
    nameEs: "Sofia Real Estate",
    nameEn: "Sofia Real Estate",
    taglineEs: "IA que vende propiedades mientras duermes",
    taglineEn: "AI that sells properties while you sleep",
    descriptionEs:
      "Calificación de leads 24/7, respuestas instantáneas en WhatsApp, seguimiento automático, generación de documentos.",
    descriptionEn:
      "24/7 lead qualification, instant WhatsApp responses, automatic follow-up, document generation.",
    category: "flagship",
    subcategory: "real-estate",
    techStack: ["Next.js 16", "Supabase", "Claude AI", "WhatsApp", "Twilio"],
    liveUrl: "https://sofia-realestate.vercel.app",
    colorAccent: "#0891b2",
    isActive: true,
    isFeatured: true,
  },
  {
    slug: "pangea",
    nameEs: "Pangea Platform",
    nameEn: "Pangea Platform",
    taglineEs: "Infraestructura global de IA",
    taglineEn: "Global AI infrastructure",
    descriptionEs: "Plataforma core de MachineMind para automatización AI.",
    descriptionEn: "MachineMind core platform for AI automation.",
    category: "automation",
    subcategory: "platform",
    techStack: ["Next.js 16", "React 19", "Tailwind v4", "Supabase"],
    liveUrl: "https://pangea-xi-cyan.vercel.app",
    colorAccent: "#4f46e5",
    isActive: true,
    isFeatured: false,
  },

  // ============================================
  // AUTOMATION PLATFORMS
  // ============================================
  {
    slug: "outreach-engine",
    nameEs: "Outreach Engine",
    nameEn: "Outreach Engine",
    taglineEs: "Generación de leads y marketing automatizado",
    taglineEn: "Lead generation and automated marketing",
    category: "automation",
    subcategory: "marketing",
    techStack: ["Next.js 16", "NextAuth", "Google APIs", "XLSX"],
    liveUrl: null,
    colorAccent: "#10b981",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "pulse",
    nameEs: "Pulse",
    nameEn: "Pulse",
    taglineEs: "Analítica y monitoreo en tiempo real",
    taglineEn: "Real-time analytics and monitoring",
    category: "automation",
    subcategory: "analytics",
    techStack: ["Next.js 16", "Supabase", "Zustand", "date-fns"],
    liveUrl: null,
    colorAccent: "#8b5cf6",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "voxlink",
    nameEs: "VoxLink",
    nameEn: "VoxLink",
    taglineEs: "Plataforma de comunicación voz/video",
    taglineEn: "Voice/video communication platform",
    category: "automation",
    subcategory: "communication",
    techStack: ["Next.js 14", "Daily.co", "PeerJS", "WebRTC"],
    liveUrl: null,
    colorAccent: "#06b6d4",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "contentengine",
    nameEs: "Content Engine",
    nameEn: "Content Engine",
    taglineEs: "Sistema de gestión de contenido",
    taglineEn: "Content management system",
    category: "automation",
    subcategory: "content",
    techStack: ["Next.js 16", "Supabase", "date-fns"],
    liveUrl: null,
    colorAccent: "#f97316",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "moneymachine",
    nameEs: "MoneyMachine",
    nameEn: "MoneyMachine",
    taglineEs: "Gestión financiera automatizada",
    taglineEn: "Automated financial management",
    category: "automation",
    subcategory: "finance",
    techStack: ["Next.js 16", "Supabase", "Resend"],
    liveUrl: null,
    colorAccent: "#22c55e",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "website-factory",
    nameEs: "Website Factory",
    nameEn: "Website Factory",
    taglineEs: "Generador de sitios web desde config",
    taglineEn: "Website generator from config",
    category: "automation",
    subcategory: "tools",
    techStack: ["Node.js", "Templates"],
    liveUrl: null,
    colorAccent: "#3b82f6",
    isActive: true,
    isFeatured: false,
  },

  // ============================================
  // ENTERPRISE SOLUTIONS
  // ============================================
  {
    slug: "cartagena-concierge",
    nameEs: "Cartagena Concierge",
    nameEn: "Cartagena Concierge",
    taglineEs: "Sistema de reservas turísticas",
    taglineEn: "Tourist booking system",
    category: "enterprise",
    subcategory: "tourism",
    techStack: ["Next.js 16", "Supabase", "Framer Motion"],
    liveUrl: null,
    colorAccent: "#0891b2",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "concierge-command-center",
    nameEs: "Concierge Command Center",
    nameEn: "Concierge Command Center",
    taglineEs: "Dashboard unificado de concierges",
    taglineEn: "Unified concierge dashboard",
    category: "enterprise",
    subcategory: "management",
    techStack: ["Next.js 16", "Supabase"],
    liveUrl: null,
    colorAccent: "#6366f1",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "openclaw",
    nameEs: "OpenClaw",
    nameEn: "OpenClaw",
    taglineEs: "Gateway multi-canal para WhatsApp",
    taglineEn: "Multi-channel WhatsApp gateway",
    category: "enterprise",
    subcategory: "messaging",
    techStack: ["TypeScript", "Baileys", "RPC", "Node.js 22+"],
    liveUrl: null,
    colorAccent: "#16a34a",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "lavanderia-oriental",
    nameEs: "Lavandería Oriental",
    nameEn: "Lavandería Oriental",
    taglineEs: "Sistema de gestión de lavandería",
    taglineEn: "Laundry management system",
    category: "enterprise",
    subcategory: "services",
    techStack: ["Express", "React", "Drizzle", "PostgreSQL", "OpenAI"],
    liveUrl: null,
    colorAccent: "#0ea5e9",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "csj-modernizacion",
    nameEs: "CSJ Modernización",
    nameEn: "CSJ Modernization",
    taglineEs: "Plataforma de modernización judicial",
    taglineEn: "Judicial modernization platform",
    category: "enterprise",
    subcategory: "government",
    techStack: ["Next.js 16", "Tailwind"],
    liveUrl: null,
    colorAccent: "#1e40af",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "csj-panel-ejecutivo",
    nameEs: "CSJ Panel Ejecutivo",
    nameEn: "CSJ Executive Panel",
    taglineEs: "Dashboard ejecutivo judicial",
    taglineEn: "Judicial executive dashboard",
    category: "enterprise",
    subcategory: "government",
    techStack: ["Next.js 14", "React 18", "Tailwind"],
    liveUrl: null,
    colorAccent: "#1e3a5f",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "wuilo",
    nameEs: "Wuilo",
    nameEn: "Wuilo",
    taglineEs: "Plataforma de servicios",
    taglineEn: "Services platform",
    category: "enterprise",
    subcategory: "services",
    techStack: ["Next.js 16", "Supabase"],
    liveUrl: null,
    colorAccent: "#7c3aed",
    isActive: true,
    isFeatured: false,
  },
  {
    slug: "xclusive-platform",
    nameEs: "XClusive Platform",
    nameEn: "XClusive Platform",
    taglineEs: "Plataforma de membresía premium",
    taglineEn: "Premium membership platform",
    category: "enterprise",
    subcategory: "membership",
    techStack: ["Next.js 16", "Supabase", "date-fns"],
    liveUrl: null,
    colorAccent: "#be123c",
    isActive: true,
    isFeatured: false,
  },
];

// Helper functions
export function getProjectsByCategory(category: ProjectCategory): Project[] {
  return projects.filter((p) => p.category === category && p.isActive);
}

export function getFeaturedProjects(): Project[] {
  return projects.filter((p) => p.isFeatured && p.isActive);
}

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getActiveProjectCount(): number {
  return projects.filter((p) => p.isActive).length;
}

export function getProjectsWithLiveUrl(): Project[] {
  return projects.filter((p) => p.liveUrl && p.isActive);
}

// Category labels
export const categoryLabels: Record<
  ProjectCategory,
  { es: string; en: string }
> = {
  flagship: { es: "Insignia", en: "Flagship" },
  demo: { es: "Demos", en: "Demos" },
  automation: { es: "Automatización", en: "Automation" },
  enterprise: { es: "Empresarial", en: "Enterprise" },
};
