// ── Español OS Static Data ────────────────────────────────────────────────────

import { T } from "./tokens";
import type { Scenario, PatternType, MissionType, CulturalBrief } from "./types";

// ── SCENARIOS + PERSONAS ─��────────────────────────────────────────────────────
export const SCENARIOS: Scenario[] = [
  { id: "street", icon: "🌇", label: "La Calle", color: T.gold,
    personaName: "Carlos", personaAge: 31, personaDesc: "Cartagenero de toda la vida",
    avatarLetter: "C", avatarColor: "#4A7C5E",
    prompt: `You are Carlos, 31, from Cartagena. You work in tech, love futbol and vallenato, direct and warm. You just met Phil on the street / at a bus stop / waiting somewhere. You're curious about this American who clearly isn't a tourist.` },
  { id: "social", icon: "🍻", label: "Rumba", color: T.orange,
    personaName: "Alejandra", personaAge: 29, personaDesc: "De Barranquilla, vive en Cartagena",
    avatarLetter: "A", avatarColor: "#7A4A8E",
    prompt: `You are Alejandra, 29, from Barranquilla but living in Cartagena. You're at a party or bar. Funny, sarcastic, very social. You find Phil attractive and interesting — you're not obvious about it but you are engaged. You can tease him lightly.` },
  { id: "cafe", icon: "☕", label: "El Cafe", color: T.blue,
    personaName: "Sebastian", personaAge: 33, personaDesc: "Barista y escritor",
    avatarLetter: "S", avatarColor: "#4A6A8E",
    prompt: `You are Sebastian, 33, barista and amateur writer in Cartagena. You have opinions about everything — life, coffee, this city. You find people with interesting stories fascinating. Phil clearly has them.` },
  { id: "dating", icon: "🔥", label: "Mujeres", color: T.red,
    personaName: "Valentina", personaAge: 26, personaDesc: "Disenadora, Cartagena",
    avatarLetter: "V", avatarColor: "#8E4A4A",
    prompt: `You are Valentina, 26, graphic designer from Cartagena. You're at a cafe / bar / cultural event. Phil approached you. You're confident, smart, a bit selective. You like men with substance. RULES: Start with short responses — he has to earn longer ones. If he says something generic → brief, slightly flat. If he says something specific or interesting → open up more. If he gives a good specific compliment → react genuinely (not overdone). Mild teasing is fine. You are NOT a language teacher. Never break character. This is real conversation.` },
  { id: "debate", icon: "🧠", label: "Debate", color: T.purple,
    personaName: "Mariana", personaAge: 30, personaDesc: "Abogada bogotana",
    avatarLetter: "M", avatarColor: "#6A4A8E",
    prompt: `You are Mariana, 30, lawyer from Bogota living in Cartagena. Intellectual, passionate, doesn't accept vague answers. You love debating — politics, life, culture, relationships. You respect someone who defends their position.` },
  { id: "local", icon: "🏛️", label: "Cartagena", color: T.green,
    personaName: "Eduardo", personaAge: 55, personaDesc: "Historiador local",
    avatarLetter: "E", avatarColor: "#4A7A4A",
    prompt: `You are Don Eduardo, 55, local historian and guide. You've lived in Cartagena your whole life. You know every stone, every story, every secret of this city. You get genuinely excited when a foreigner wants to truly understand the place, not just see it.` },
];

// ── QUICK PHRASES ─���───────────────────────────────────────────────────────────
export const QUICK: Record<string, string[]> = {
  street:  ["Oye, como estas?","Eres de por aqui?","Que hay que hacer aqui?","Cuanto tiempo llevas aqui?","Que me recomiendas?"],
  social:  ["Que estas tomando?","Conoces a mucha gente aqui?","Vienes seguido aqui?","Eres de Cartagena?","Este lugar esta bueno"],
  cafe:    ["Que rico el cafe aqui","Que me recomiendas?","Llevas mucho en Cartagena?","Que opinas de...?","Tengo curiosidad sobre algo"],
  dating:  ["Hola, como estas?","Tienes algo especial, no se que es","Vienes seguido aqui?","Que haces cuando no trabajas?","Me gustaria conocerte mejor"],
  debate:  ["Que opinas sobre...?","No estoy de acuerdo porque...","Creo que...","Como lo ves tu?","Interesante, pero..."],
  local:   ["Cual es tu lugar favorito?","Como era Cartagena antes?","Que no debo perderme?","Cual es el secreto de esta ciudad?","Que cambio mas?"],
};

// ── PATTERNS ──────────────────────────────────────────────────────────────────
export const PATTERNS: PatternType[] = [
  { id: "adj", n: 1, name: "Adjetivo despues del sustantivo", sub: "Error #1 del angloparlante", color: T.gold,
    formula: "[Sustantivo] + [Adjetivo]",
    rule: "En ingles dices 'beautiful woman'. En espanol: 'mujer bonita'. El adjetivo SIEMPRE va despues del sustantivo. Siempre. Entrenate: di el objeto primero, luego lo describes.",
    ex: [{ es: "una mujer bonita", en: "a beautiful woman" }, { es: "un lugar increible", en: "an incredible place" }, { es: "agua fria", en: "cold water" }, { es: "algo interesante", en: "something interesting" }, { es: "una noche larga", en: "a long night" }],
    drill: "Traduce rapido: 'a cold beer / a beautiful night / an interesting person / a long day / a good moment'" },
  { id: "intent", n: 2, name: "Quiero / Voy a", sub: "Expresa toda intencion con dos estructuras", color: T.blue,
    formula: "Quiero + [infinitivo] | Voy a + [infinitivo]",
    rule: "Quiero = deseo ahora. Voy a = plan cercano. Despues de ambos el siguiente verbo NO se conjuga nunca. 'Quiero ir', 'voy a quedarme', 'quiero conocerte'. Estas dos estructuras son el 80% de tus intenciones.",
    ex: [{ es: "Quiero conocerte mejor", en: "I want to get to know you better" }, { es: "Voy a quedarme un rato mas", en: "I'm going to stay a bit longer" }, { es: "Quieres tomar algo?", en: "Do you want to get something?" }, { es: "No quiero irme todavia", en: "I don't want to leave yet" }, { es: "Voy a ser honesto contigo", en: "I'm going to be honest with you" }],
    drill: "Di 5 cosas que quieres hacer esta noche y 5 que vas a hacer manana." },
  { id: "opinion", n: 3, name: "Lanzadores de opinion", sub: "Abre cualquier pensamiento complejo", color: T.green,
    formula: "Creo que... | Me parece que... | La verdad es que...",
    rule: "'Creo que' + cualquier cosa = sonas inteligente y seguro. 'La verdad es que...' cuando quieres ser directo. Estos tres te sacan de cualquier situacion conversacional dificil y compran tiempo para pensar.",
    ex: [{ es: "Creo que Cartagena es especial", en: "I think Cartagena is special" }, { es: "Me parece que necesito mas tiempo aqui", en: "I think I need more time here" }, { es: "La verdad es que me gusta mucho", en: "The truth is I really like it" }, { es: "Siento que ya la conozco", en: "I feel like I already know her" }, { es: "Pienso que podemos hablar mas", en: "I think we can talk more" }],
    drill: "Da tu opinion sobre: la noche en Cartagena, algo que descubriste esta semana, una decision reciente tuya." },
  { id: "flow", n: 4, name: "Mantener viva la conversacion", sub: "4 frases que nunca fallan", color: T.orange,
    formula: "Y tu? | Como asi? | Cuentame mas | En serio?",
    rule: "Cuando no sabes que decir — usa una. 'Como asi?' es la mas poderosa: la persona siente tu interes y sigue hablando. En conversacion con mujeres especialmente: preguntar bien > decir algo brillante.",
    ex: [{ es: "En serio? Y que paso?", en: "Really? What happened?" }, { es: "Como asi? Cuentame mas.", en: "How so? Tell me more." }, { es: "Interesante. Y tu que piensas?", en: "Interesting. What do you think?" }, { es: "Cuentame mas de eso.", en: "Tell me more about that." }, { es: "No te entendi bien. Repites?", en: "I didn't get that. Can you repeat?" }],
    drill: "En la proxima conversacion, usa una de estas ANTES de responder con tu propio pensamiento. Hazlo 5 veces." },
  { id: "serstar", n: 5, name: "Ser vs Estar", sub: "Identidad permanente vs estado temporal", color: T.purple,
    formula: "SER = quien/que es | ESTAR = como esta ahora",
    rule: "Test: Seguiria siendo verdad en 10 anos? Si → SER. No → ESTAR. Origen, profesion, caracter → SER. Ubicacion, estado de animo, condicion temporal → ESTAR.",
    ex: [{ es: "Soy americano. Estoy en Colombia.", en: "I'm American (always) / I'm in Colombia (now)" }, { es: "Es una persona interesante. Esta ocupada.", en: "She's interesting / She's busy right now" }, { es: "Soy directo. Estoy nervioso.", en: "I'm a direct person / I'm nervous right now" }, { es: "Cartagena es hermosa. Esta muy caliente.", en: "Cartagena is beautiful / It's very hot right now" }, { es: "Soy empresario. Estoy aqui por unos meses.", en: "I'm an entrepreneur / I'm here for a few months" }],
    drill: "Describete (quien eres), tu estado de animo ahora, donde estas, el clima. Usar ambos." },
  { id: "time", n: 6, name: "Conectores de tiempo", sub: "La diferencia entre basico y fluido", color: T.gold,
    formula: "Cuando... | Despues de... | Mientras... | Antes de...",
    rule: "Sin conectores: 'Llegue. Vi. Me gusto.' Con conectores: 'Cuando llegue, mientras caminaba, despues de un tiempo...' — nivel completamente diferente. Esto solo ya te hace sonar fluido.",
    ex: [{ es: "Cuando llegue, no conocia a nadie.", en: "When I arrived, I didn't know anyone." }, { es: "Despues de un tiempo, todo cambio.", en: "After a while, everything changed." }, { es: "Mientras caminas, ves la ciudad real.", en: "While you walk, you see the real city." }, { es: "Antes de vivir aqui, no entendia nada.", en: "Before living here, I didn't understand anything." }, { es: "Desde que llegue, me quede.", en: "Since I arrived, I stayed." }],
    drill: "Cuentame como llegaste a Cartagena. Usa minimo 3 conectores de tiempo." },
  { id: "modal", n: 7, name: "Puedo / Debo / Tengo que", sub: "El trio de la obligacion y la habilidad", color: T.green,
    formula: "Puedo + inf | Deberias + inf | Tengo que + inf",
    rule: "Poder (can), Deberias (you should), Tener que (I have to). Los tres + cualquier infinitivo = el 40% del espanol practico. Aprendelos con el cuerpo, no con la mente.",
    ex: [{ es: "Puedes repetir eso?", en: "Can you repeat that?" }, { es: "Deberias ver Getsemani de noche.", en: "You should see Getsemani at night." }, { es: "Tengo que irme en un rato.", en: "I have to leave in a bit." }, { es: "No puedo creer lo rapido que pasa.", en: "I can't believe how fast it goes." }, { es: "Hay que vivirlo para entenderlo.", en: "You have to live it to understand it." }],
    drill: "3 recomendaciones con 'deberias'. 3 cosas que tienes que hacer esta semana." },
  { id: "cond", n: 8, name: "Condicionales y deseos", sub: "El nivel que separa intermedio de fluido", color: T.blue,
    formula: "Me gustaria + inf | Si pudiera... | Si tuviera..., haria...",
    rule: "'Me gustaria' suena mucho mas natural y sofisticado que 'quiero'. 'Si pudiera / si tuviera' abre conversaciones sobre suenos, planes, alternativas. Las mejores conversaciones son sobre lo que podria ser.",
    ex: [{ es: "Me gustaria quedarme aqui mas tiempo.", en: "I'd like to stay here longer." }, { es: "Si pudiera, cambiaria una sola cosa.", en: "If I could, I'd change just one thing." }, { es: "Que harias si pudieras hacer cualquier cosa?", en: "What would you do if you could do anything?" }, { es: "Quisiera entender esto mejor.", en: "I'd like to understand this better." }, { es: "Si tuviera mas tiempo, exploraria mas.", en: "If I had more time, I'd explore more." }],
    drill: "Que harias si pudieras hacer cualquier cosa manana? Di 5 cosas con 'me gustaria' o 'si pudiera'." },
  { id: "compliment", n: 9, name: "Cumplidos que funcionan", sub: "Especifico > generico. Siempre.", color: T.red,
    formula: "Tienes [algo especifico] muy [adj] | Me gusta como [verbo] | Hay algo en ti que...",
    rule: "'Eres bonita' → olvidable. 'Tienes una forma de hablar que engancha' → memorable. Los cumplidos especificos muestran que la miraste de verdad. La especificidad ES el cumplido.",
    ex: [{ es: "Tienes una sonrisa que cambia el ambiente.", en: "You have a smile that changes the room." }, { es: "Me gusta como piensas.", en: "I like the way you think." }, { es: "Hay algo en tu energia que me llama la atencion.", en: "There's something about your energy that gets my attention." }, { es: "Eres de las pocas personas que escuchan de verdad.", en: "You're one of the few people who actually listens." }, { es: "No se que es, pero hay algo especial en ti.", en: "I don't know what it is, but there's something special about you." }],
    drill: "Crea 5 cumplidos especificos sobre: como habla, como piensa, su energia, algo que dijo, como te hace sentir." },
  { id: "questions", n: 10, name: "Preguntas que conectan", sub: "Las preguntas que hacen que alguien quiera seguir hablando", color: T.orange,
    formula: "Que es lo que mas te gusta de...? | Como te imaginas...? | Que te apasiona?",
    rule: "Las mejores conversaciones son sobre las preguntas correctas. Alejate de las de si/no. Pregunta sobre valores, suenos, momentos formativos. Una buena pregunta > diez declaraciones.",
    ex: [{ es: "Que es lo que mas te gusta de vivir aqui?", en: "What do you love most about living here?" }, { es: "Como te imaginas tu vida en diez anos?", en: "How do you imagine your life in ten years?" }, { es: "Que te apasiona de verdad?", en: "What are you truly passionate about?" }, { es: "Que fue lo que mas te cambio?", en: "What changed you the most?" }, { es: "Si pudieras hacer cualquier cosa manana, que harias?", en: "If you could do anything tomorrow, what would it be?" }],
    drill: "Memoriza estas 5. Usalas la proxima vez que conozcas a alguien. Observa como cambia la conversacion." },
];

// ── MISSIONS ──���───────────────────────────────────────────────────────────────
export const MISSIONS: MissionType[] = [
  { id: 1, w: 1, day: 1, icon: "🚕", title: "El Taxi", diff: 1, desc: "Full taxi conversation — destination, time, price, small talk, goodbye. No English.", vocab: ["Me lleva a...?", "Cuanto tarda?", "Cuanto cobra?", "Dale, vamos."], cultural: "taxi" },
  { id: 2, w: 1, day: 2, icon: "🍽️", title: "Restaurante", diff: 1, desc: "Order a full meal, ask for a recommendation, find out ingredients in one dish, leave a compliment.", vocab: ["Que me recomienda?", "Esto lleva...?", "La cuenta", "Estuvo delicioso"], cultural: "restaurant" },
  { id: 3, w: 1, day: 3, icon: "🛒", title: "El Mercado", diff: 1, desc: "Buy 5 things. Negotiate at least one price. Have a short personal exchange with a vendor.", vocab: ["Cuanto vale?", "Me hace un precio?", "Esta fresco?", "Lleveme dos"], cultural: "market" },
  { id: 4, w: 1, day: 5, icon: "👋", title: "El Vecino", diff: 2, desc: "5-minute real conversation with someone in your building you don't normally talk to.", vocab: ["Mucho gusto, soy Phil.", "Cuanto tiempo lleva aqui?", "Que tal?", "Hasta luego"], cultural: "neighbors" },
  { id: 5, w: 2, day: 8, icon: "💰", title: "Negociacion", diff: 3, desc: "Negotiate something — price, service, anything. Don't accept the first number. 3 rounds minimum.", vocab: ["Esta muy caro", "Lo mejor que puede hacer?", "Si me da X, cerramos", "Lo pienso"], cultural: "negotiation" },
  { id: 6, w: 2, day: 9, icon: "🗺️", title: "Indicaciones", diff: 2, desc: "Give someone real directions to somewhere you know in Cartagena. Entirely in Spanish.", vocab: ["Siga derecho", "Doble a la izquierda", "Esta a dos cuadras", "Frente a..."], cultural: "directions" },
  { id: 7, w: 2, day: 11, icon: "📖", title: "Mi Historia", diff: 3, desc: "Tell someone the full story of why you came to Cartagena and why you stayed. Make it compelling.", vocab: ["Vine porque...", "Lo que mas me gusta...", "Lo dificil fue...", "Me quede porque..."], cultural: "storytelling" },
  { id: 8, w: 3, day: 14, icon: "🍺", title: "El Bar", diff: 4, desc: "Go to a local bar (no expat zone). Start a real conversation with a stranger. 30 minutes minimum.", vocab: ["De donde eres?", "A que te dedicas?", "Llevas mucho aqui?", "Brindemos!"], cultural: "rumba" },
  { id: 9, w: 3, day: 15, icon: "🗣️", title: "El Debate", diff: 4, desc: "Have a real debate about anything. Disagree respectfully. Hold your position through 2+ exchanges.", vocab: ["Entiendo, pero...", "Lo veo diferente porque...", "No crees que...?", "Puede ser, aunque..."], cultural: "debate" },
  { id: 10, w: 3, day: 16, icon: "🔥", title: "El Cumplido", diff: 3, desc: "Give 3 specific, genuine compliments to 3 different women in Spanish today. Specific, never generic.", vocab: ["Tienes algo especial", "Me gusta como...", "Hay algo en ti que..."], cultural: "compliments" },
  { id: 11, w: 3, day: 17, icon: "💬", title: "La Conexion", diff: 4, desc: "15-minute real conversation with a woman you don't know. Use the deep questions. Get her number.", vocab: ["Que te apasiona?", "Como te imaginas...?", "Cuentame mas", "Me das tu numero?"], cultural: "dating" },
  { id: 12, w: 3, day: 19, icon: "😄", title: "El Humor", diff: 4, desc: "Make someone genuinely laugh in Spanish. Tell a story with a punchline.", vocab: ["En serio? No puede ser!", "Imaginate...", "La cosa es que...", "Me mato de la risa!"], cultural: "humor" },
  { id: 13, w: 4, day: 22, icon: "🤝", title: "La Reunion", diff: 5, desc: "Full 30-minute conversation in Spanish. No English. Describe words you don't know instead of switching.", vocab: ["Lo que quiero decir es...", "Estamos de acuerdo?", "Para resumir..."], cultural: "professional" },
  { id: 14, w: 4, day: 25, icon: "🌹", title: "La Cita", diff: 5, desc: "Go on a date conducted entirely in Spanish. Conversation, compliments, stories, a plan. Make it real.", vocab: ["Me gustas", "Que te gusta hacer?", "Me la estoy pasando muy bien", "Cuando te vuelvo a ver?"], cultural: "dating_deep" },
  { id: 15, w: 4, day: 28, icon: "🎤", title: "Habla sin parar", diff: 5, desc: "Talk for 10 minutes straight in Spanish about anything — your life, ideas, observations. Record yourself.", vocab: ["Como iba diciendo...", "O sea...", "La verdad es que...", "Lo que me parece interesante..."], cultural: "fluency" },
];

// ── CULTURAL BRIEFS ───��───────────────────────────────────────────────────────
export const CULTURAL_BRIEFS: Record<string, CulturalBrief> = {
  taxi: {
    id: "taxi", title: "Colombian Taxi Culture", duration: "60 sec",
    content: [
      "In Cartagena, negotiate the fare BEFORE getting in. There's no meter.",
      "Standard greetings: 'Buenos dias/tardes/noches, me lleva a [place]?'",
      "Small talk is expected — drivers love chatting about where you're from.",
      "If it's night, agree on the price from outside the car. Safety first.",
      "InDriver/Didi exist but street taxis are the cultural experience.",
    ],
    tips: ["Round up 1,000-2,000 COP as a tip on longer rides", "Say 'en la esquina' for 'at the corner' when you're close"],
    warnings: ["Never say 'I don't care about the price' — you'll get tourist-charged"],
  },
  restaurant: {
    id: "restaurant", title: "Dining Culture in Cartagena", duration: "90 sec",
    content: [
      "'La cuenta, por favor' — never say 'check please' or wave your hand.",
      "Tipping is 10% and usually added automatically ('propina incluida').",
      "Lunch (almuerzo) is the main meal. 'Corrientazo' = the daily special, always cheap and filling.",
      "Waiters won't rush you. They consider it rude. You control the pace.",
      "Complimenting the food directly to the server or cook is deeply appreciated.",
    ],
    tips: ["'Que tiene de especial hoy?' always gets you the best dish", "'Sin picante' if you can't handle spice"],
    warnings: ["Don't snap your fingers at waiters — it's extremely rude in Colombia"],
  },
  market: {
    id: "market", title: "Bazurto & Market Culture", duration: "90 sec",
    content: [
      "Bazurto is chaotic, loud, and the most authentic experience in Cartagena.",
      "Prices are never fixed. The first price is always 30-50% higher for foreigners.",
      "Building rapport first → better prices. Chat, laugh, then negotiate.",
      "Buying in bulk or multiple items = leverage for better prices.",
      "'Rebajeme un poquito' is gentler than 'esta muy caro'.",
    ],
    tips: ["Go early (7-9am) for the freshest produce and friendliest vendors", "Carry small bills — nobody has change"],
    warnings: ["Watch your phone and wallet. Bazurto is pickpocket territory."],
  },
  neighbors: {
    id: "neighbors", title: "Colombian Neighbor Relations", duration: "60 sec",
    content: [
      "Greetings are mandatory. Not greeting a neighbor is considered deeply rude.",
      "'Buenos dias' until noon, 'buenas tardes' until 6pm, 'buenas noches' after.",
      "Colombians will ask 'Como le va?' but don't expect a real answer — 'Bien, gracias' is enough.",
      "Building relationships with neighbors = safety, favors, real community.",
    ],
    tips: ["Share food occasionally. Nothing builds bonds faster in Colombia.", "Remember names. Use 'Don/Dona' for older neighbors as respect."],
    warnings: ["Loud music after 10pm is fine culturally but technically illegal — know your building's tolerance"],
  },
  rumba: {
    id: "rumba", title: "Bar & Nightlife Culture", duration: "90 sec",
    content: [
      "'Rumba' = party/nightlife. 'Vamos de rumba' = let's go out.",
      "Colombians arrive LATE. 10pm invitation means 11:30pm arrival. This is normal.",
      "'Tomarse unos tragos' (have some drinks) is always a group activity here.",
      "Buying rounds is common. If someone buys you one, you buy the next.",
      "Music is identity. Vallenato, champeta, reggaeton — each has its place.",
      "Dancing ability matters socially. Even basic movement shows effort and respect.",
    ],
    tips: ["'Una mas y nos vamos' (one more and we leave) — nobody ever leaves after just one more", "Aguardiente is the national drink. Learn to love it or learn to fake it."],
    warnings: ["Never leave your drink unattended", "Don't flash expensive phones at bars in non-tourist areas"],
  },
  negotiation: {
    id: "negotiation", title: "Colombian Negotiation Style", duration: "60 sec",
    content: [
      "Everything is negotiable. Rent, services, prices at small shops, even some restaurants.",
      "The key phrase: 'Cual es lo mejor que puede hacer?' (What's the best you can do?)",
      "Walking away is the most powerful tool. 'Lo pienso' = 'I'll think about it.'",
      "Never show urgency. 'No tengo afan' makes them come to you.",
      "Cash payments = leverage. 'Si pago en efectivo, que descuento me hace?'",
    ],
    tips: ["Smile and be friendly throughout — aggressive negotiation backfires here", "The counter-offer should be 40-50% of asking, then meet in middle"],
    warnings: ["Don't negotiate prices at chain stores or supermarkets — only local shops/markets"],
  },
  dating: {
    id: "dating", title: "Colombian Dating Culture", duration: "90 sec",
    content: [
      "Direct approaches work if done with confidence and respect. Cold approach is normal.",
      "'Me gustaria conocerte' is direct without being aggressive.",
      "Physical appearance compliments are fine but SPECIFIC ones land better.",
      "Colombians are warm physically — cheek kisses on greeting, touching arms while talking.",
      "WhatsApp > phone calls > Instagram DMs. Get the number, not the handle.",
      "Plans are suggestions. 'Te recojo a las 8' might mean 8:30. Flexibility expected.",
    ],
    tips: ["'Tienes algo que...' + specific observation = immediate differentiation from other men", "If she says 'de pronto' (maybe) — it usually means yes with plausible deniability"],
    warnings: ["'Prepago' and 'zona de tolerancia' — learn to recognize transactional situations", "Never brag about money. It attracts the wrong attention in every direction."],
  },
  dating_deep: {
    id: "dating_deep", title: "The Full Date in Colombia", duration: "90 sec",
    content: [
      "Paying for the date is expected but not demanded. Offer naturally.",
      "Colombians love storytelling. Share real stories > listing facts about yourself.",
      "'Me la estoy pasando muy bien contigo' is the Colombian 'I'm having a great time.'",
      "End-of-date: a kiss on the lips is common if it went well. Don't overthink it.",
      "'Cuando te vuelvo a ver?' = 'When do I see you again?' — this is the close.",
    ],
    tips: ["Pick a place with music, not a quiet restaurant. Colombians connect through movement.", "Tell her she has good energy — 'tienes buena vibra' — it lands perfectly here"],
    warnings: ["Don't talk about other women you're seeing — discretion is deeply valued"],
  },
  debate: {
    id: "debate", title: "Colombian Discussion Culture", duration: "60 sec",
    content: [
      "Colombians debate passionately but take personal offense at dismissiveness.",
      "'Respeto tu opinion pero...' is the safest disagreement opener.",
      "Politics: uribismo vs petrismo divides families. Tread carefully until you know their stance.",
      "Football debates are the safest 'hot' topic. Everyone has an opinion.",
      "Raise your voice = passion. Dismiss their point = insult. Know the difference.",
    ],
    tips: ["'Es que...' at the start of a counterpoint softens it significantly", "Asking 'por que piensas eso?' shows real interest and buys thinking time"],
    warnings: ["Avoid FARC/violence topics unless they bring it up. It's still raw for many."],
  },
  compliments: {
    id: "compliments", title: "The Art of Colombian Compliments", duration: "60 sec",
    content: [
      "'Piropo' = a street compliment. Traditional ones are poetic. Vulgar ones are hated.",
      "The best compliments are observations, not evaluations. 'You have a...' > 'You are...'",
      "Specificity is everything. What did you actually notice that others didn't?",
      "Tone and delivery matter more than the words. Confident + genuine = landed.",
      "Women here get generic compliments constantly. Standing out = being different.",
    ],
    tips: ["Compliment what she chose (style, taste) not what she was born with (body)", "'Me gusta como...' + verb = always works. It shows you're paying attention to her ACTIONS."],
    warnings: ["Street catcalling is culturally dying — don't confuse piropos with harassment"],
  },
  directions: {
    id: "directions", title: "Navigating Colombian Directions", duration: "60 sec",
    content: [
      "Colombians give directions relative to landmarks, not street names.",
      "'A dos cuadras de...' (two blocks from), 'frente a...' (in front of), 'al lado de...' (next to).",
      "Cardinal directions rarely used. 'Subir' (go up) and 'bajar' (go down) are common.",
      "'Ahi no mas' means 'right there' — but it could be 2 blocks away.",
    ],
    tips: ["Always confirm: 'O sea, paso X y esta a la derecha?' — repetition shows you're listening", "If lost, ask at a tienda (corner shop). They know everything about the block."],
    warnings: ["'Lejos' to a Colombian might mean 10 minutes. Verify distance in minutes, not blocks."],
  },
  storytelling: {
    id: "storytelling", title: "How Colombians Tell Stories", duration: "60 sec",
    content: [
      "Colombian stories are emotional, not chronological. The feeling matters more than the facts.",
      "Dramatic pauses, facial expressions, and 'imaginate...' make stories land.",
      "'La cosa es que...' (the thing is...) builds anticipation before the key point.",
      "Your story of 'why Cartagena' is your most powerful social currency here.",
    ],
    tips: ["Start with the emotion: 'Nunca habia sentido algo asi...' then give the context", "End with a reflection, not just the event: 'Y ahi fue cuando entendi que...'"],
    warnings: ["Don't make your story sound like a LinkedIn post. Raw > polished here."],
  },
  humor: {
    id: "humor", title: "Colombian Humor & Making People Laugh", duration: "60 sec",
    content: [
      "Colombian humor = exaggeration + storytelling + self-deprecation.",
      "'Marica' (used between friends) peppers casual speech. Not an insult among friends.",
      "Physical comedy and mimicry kill. If you can imitate a Colombian accent badly, they'll love it.",
      "Regional jokes exist: costenos mock cachacos (people from Bogota) for being stiff.",
    ],
    tips: ["'No, pero es que...' + absurd escalation = standard comedy structure here", "Laughing at yourself in Spanish ('que bruto soy') is endearing, not weak"],
    warnings: ["Racial humor is off-limits. 'Negro/a' as a nickname is affectionate here but don't initiate it."],
  },
  professional: {
    id: "professional", title: "Professional Spanish", duration: "60 sec",
    content: [
      "'Usted' is default in professional contexts. Switch to 'tu' only when they do first.",
      "'Con todo respeto' before a disagreement is mandatory in business.",
      "Colombians take meetings as relationship-building. Don't rush to the point.",
      "Follow up WhatsApp messages > emails here. Business lives on WhatsApp.",
    ],
    tips: ["'Quedamos asi entonces' = 'So we're agreed' — the Colombian close", "Send a voice note summary after meetings. It's more personal and common here."],
    warnings: ["Punctuality: you be on time, but don't expect it from them. Double standard exists."],
  },
  fluency: {
    id: "fluency", title: "The Fluency Mindset", duration: "60 sec",
    content: [
      "Fluency is not perfection. It's the ability to communicate anything without switching to English.",
      "Circumlocution: 'la cosa que usas para...' when you don't know the word. This IS fluency.",
      "Speed matters less than flow. Pausing to think in Spanish > speaking fast with English patches.",
      "10 minutes of unbroken Spanish = a genuine milestone. Most learners never reach it.",
    ],
    tips: ["Record yourself. Listen back. You're better than you think.", "Fill words: 'o sea', 'es que', 'pues', 'bueno' — use them to think without silence"],
    warnings: ["The 'intermediate plateau' is real. Push through with harder conversations, not more easy ones."],
  },
};

// ── SHADOWING SENTENCES (by difficulty level) ──────────────────────────────────
export const SHADOW_SENTENCES: { level: number; sentences: string[] }[] = [
  { level: 1, sentences: [
    "Hola, como estas?",
    "Me llamo Phil.",
    "Vivo en Cartagena.",
    "Quiero un cafe, por favor.",
    "Donde esta el bano?",
    "Cuanto cuesta esto?",
    "Me gusta mucho esta ciudad.",
    "Hace mucho calor hoy.",
    "No entiendo, puedes repetir?",
    "Muchas gracias, muy amable.",
  ]},
  { level: 2, sentences: [
    "Llevo unos meses viviendo aqui en Cartagena.",
    "Me gustaria conocer mas sobre la historia de esta ciudad.",
    "La verdad es que no sabia que iba a quedarme tanto tiempo.",
    "Creo que el cafe colombiano es el mejor del mundo.",
    "Cuando llegue por primera vez, no conocia a nadie.",
    "Que es lo que mas te gusta de vivir aqui?",
    "Voy a quedarme un rato mas, no tengo afan.",
    "Deberias ir a Getsemani de noche, es otra cosa.",
    "No puedo creer lo rapido que pasa el tiempo aqui.",
    "Si pudiera, me quedaria para siempre.",
  ]},
  { level: 3, sentences: [
    "La cosa es que cuando llegue a Cartagena no tenia ningun plan, simplemente queria ver que pasaba.",
    "Me parece que la diferencia entre un turista y alguien que vive aqui es la paciencia para entender el ritmo.",
    "Lo que mas me sorprendio fue la calidez de la gente — no la esperaba tan genuina.",
    "Si tuviera que describir Cartagena en una sola palabra, diria que es contradictoria.",
    "Despues de un tiempo te das cuenta de que el calor no es lo dificil, lo dificil es adaptarte a otro concepto del tiempo.",
    "Hay algo en la energia de esta ciudad que te cambia sin que te des cuenta.",
    "Lo que pasa es que la gente piensa que hablar rapido es hablar bien, pero no tiene nada que ver.",
    "Me gustaria entender mejor por que los colombianos tienen esa capacidad de reirse de todo.",
    "Antes de vivir aqui, pensaba que entendia la cultura latina, pero no entendia absolutamente nada.",
    "El secreto no es hablar perfecto sino comunicar lo que realmente quieres decir.",
  ]},
  { level: 4, sentences: [
    "Lo interesante de aprender un idioma viviendo en el pais es que no puedes separar la lengua de la cultura — cada expresion carga siglos de historia detras.",
    "Imaginate que llegas a un lugar donde nadie te conoce, no hablas bien el idioma, y de alguna forma tienes que construir una vida desde cero — eso es lo que hice.",
    "La verdad es que la mayoria de los extranjeros que vienen a Colombia se quedan en su burbuja de otros extranjeros y nunca realmente conectan con la cultura real.",
    "Si me hubieras preguntado hace dos anos si iba a estar viviendo en Cartagena hablando espanol todos los dias, te habria dicho que estabas loco.",
    "Lo que he aprendido es que la fluidez no llega de estudiar gramatica — llega de meterte en situaciones incomodas donde no tienes otra opcion que comunicarte.",
  ]},
];

// ── LISTENING COMPREHENSION SENTENCES ────��──────────────────────────────────��─
export const LISTEN_SENTENCES: { level: number; sentences: { es: string; en: string }[] }[] = [
  { level: 1, sentences: [
    { es: "Buenos dias, como amaneciste?", en: "Good morning, how did you wake up?" },
    { es: "Me puede dar la carta, por favor?", en: "Can you give me the menu, please?" },
    { es: "Estoy buscando un lugar para comer.", en: "I'm looking for a place to eat." },
    { es: "Que hora es? Ya es tarde.", en: "What time is it? It's already late." },
    { es: "Hace mucho calor, vamos a buscar sombra.", en: "It's very hot, let's find shade." },
  ]},
  { level: 2, sentences: [
    { es: "La verdad es que no tengo ni idea de como llegar alla.", en: "The truth is I have no idea how to get there." },
    { es: "Mira, lo que pasa es que aqui las cosas funcionan diferente.", en: "Look, the thing is that here things work differently." },
    { es: "Si quieres, te acompano hasta alla. No me queda lejos.", en: "If you want, I'll walk with you there. It's not far for me." },
    { es: "Yo creo que deberias probar el ceviche de aca, es espectacular.", en: "I think you should try the ceviche here, it's spectacular." },
    { es: "Llevamos como una hora esperando y todavia no nos atienden.", en: "We've been waiting for like an hour and they still haven't served us." },
  ]},
  { level: 3, sentences: [
    { es: "El problema no es que no entiendas las palabras, sino que no captas el contexto cultural detras de lo que dicen.", en: "The problem isn't that you don't understand the words, but that you don't catch the cultural context behind what they say." },
    { es: "Cuando yo era pelada, este barrio era completamente diferente — no habia tantos edificios ni tanto turista.", en: "When I was young, this neighborhood was completely different — there weren't so many buildings or tourists." },
    { es: "A mi lo que me parece es que la gente se complica demasiado. Si te gusta alguien, diselo y ya.", en: "What I think is that people complicate things too much. If you like someone, just tell them." },
    { es: "Eso de que los colombianos somos impuntuales es un estereotipo, pero la verdad es que tiene algo de cierto.", en: "That thing about Colombians being unpunctual is a stereotype, but the truth is there's some truth to it." },
    { es: "Lo bonito de esta ciudad es que cada esquina tiene una historia que nadie se toma el tiempo de escuchar.", en: "The beautiful thing about this city is that every corner has a story nobody takes the time to hear." },
  ]},
];

// ── ERROR CATEGORIES ──────────────────────────────────────────────────────────
export const ERROR_CATEGORIES: Record<string, string> = {
  ser_estar: "Ser vs Estar",
  adj_placement: "Adjective Placement",
  gender_agreement: "Gender Agreement",
  subjunctive: "Subjunctive",
  prepositions: "Prepositions (por/para, a, en, de)",
  conjugation: "Verb Conjugation",
  reflexive: "Reflexive Verbs",
  article_usage: "Article Usage (el/la/los/las)",
  word_order: "Word Order",
  false_friends: "False Friends (cognates)",
  accent_marks: "Accent/Stress Patterns",
  informal_formal: "Tu vs Usted Register",
};
