import test from 'node:test';
import assert from 'node:assert/strict';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import Calendar from '../../src/app/admin/web-gratis/BillingLifecycleCalendar';
import { newLifecycle, accept, approve, confirmGoLive, prepareReminder, sophiaSnapshot } from '../../src/lib/web-gratis/lifecycle/core';
const now = 1791043200, principal = { role: 'operator' as const, subject: 'fixture_operator', ownerId: 'fixture_owner', tenantId: 'fixture_tenant' };
function fixture() { const s = newLifecycle({ ownerId: principal.ownerId, tenantId: principal.tenantId, signupId: 'fixture_signup', siteId: 'fixture_site' }, 'fixture_exception'); accept(s, { ...principal, role: 'client' }, { siteVersion: 1, terms: 'fixture-v1', cents: 2000, currency: 'usd', interval: 'month', approveSiteAndGoLive: true, agreeBilling: true, remindersAgreed: true, evidence: 'fixture' }, now); approve(s, principal, 1, 'fixture', now); confirmGoLive(s, principal, { mode: 'accepted_go_live', siteId: s.siteId, signupId: s.signupId, siteVersion: 1, served: true, evidence: 'fixture' }, now); return s; }
test('admin view renders canonical calendar and separate consent/approval fields', () => { const html = renderToStaticMarkup(createElement(Calendar, { records: [{ name: 'Fixture', state: fixture() }], principal, now, timezone: 'America/El_Salvador' })); for (const phrase of ['Aceptación del cliente', 'Aprobación de Phil', 'Fin fijo de prueba', 'día 15', 'día 20', 'USD 20.00'])
    assert.ok(html.includes(phrase)); });
test('calendar cannot widen tenant ownership', () => assert.throws(() => renderToStaticMarkup(createElement(Calendar, { records: [{ name: 'Other', state: fixture() }], principal: { ...principal, tenantId: 'foreign' }, now, timezone: 'UTC' }))));
test('React escapes untrusted business names and audit evidence', () => { const html = renderToStaticMarkup(createElement(Calendar, { records: [{ name: '<script>bad()</script>', state: fixture() }], principal, now, timezone: 'UTC' })); assert.ok(!html.includes('<script>bad')); assert.ok(html.includes('&lt;script&gt;')); });
test('draft reservation idempotent and remains unsent', () => { const s = fixture(); const draft = prepareReminder(s, principal, 15, now + 15 * 86400, 'https://fixture.example.test/billing', 'UTC'); assert.equal(draft.sendEnabled, false); assert.throws(() => prepareReminder(s, principal, 15, now + 15 * 86400, 'https://fixture.example.test/billing', 'UTC')); assert.equal(s.reminders[15], 'drafted'); });
test('Sophia projection excludes bearer links and private audit evidence', () => { const s = fixture(), value = sophiaSnapshot(s, principal, now); assert.equal(value.contract, 'web_gratis_fixed_v1'); assert.equal('audit' in value, false); assert.equal('link' in value, false); assert.equal(value.trialEnd, now + 30 * 86400); });
test('reserved draft is suppressed on later enrollment, ownership handoff, or missed day', async () => { const { reminderDispatchAllowed } = await import('../../src/lib/web-gratis/lifecycle/core'); const s = fixture(); prepareReminder(s, principal, 15, now + 15 * 86400, 'https://fixture.example.test/billing', 'UTC'); assert.equal(reminderDispatchAllowed(s, 15, now + 15 * 86400), true); assert.equal(reminderDispatchAllowed(s, 15, now + 16 * 86400), false); s.enrollment = 'trialing'; assert.equal(reminderDispatchAllowed(s, 15, now + 15 * 86400), false); s.enrollment = 'none'; s.messaging = 'human_owned'; assert.equal(reminderDispatchAllowed(s, 15, now + 15 * 86400), false); });
